"""
Unit and golden tests for Part 2 — Generic Cognos Metadata and Label/Value Extraction.
"""

from pathlib import Path
import pytest

from app.services.cognos_docx_parser import parse_cognos_docx
from app.cognos.extraction.metadata_extractor import extract_metadata


@pytest.fixture
def root_dir() -> Path:
    return Path(__file__).parent.parent.parent


def test_opr016_title_value(root_dir: Path):
    doc_path = root_dir / "Report Definition - OPR.docx"
    doc = parse_cognos_docx(doc_path)
    metadata, _ = extract_metadata(doc, doc_path.name)
    assert metadata.report_title == "TPL Interface (HMS) Exception Report"
    assert metadata.report_title != "Report Title:"


def test_opr016_description_value(root_dir: Path):
    doc_path = root_dir / "Report Definition - OPR.docx"
    doc = parse_cognos_docx(doc_path)
    metadata, _ = extract_metadata(doc, doc_path.name)
    expected_desc = "This report lists the members which had errors while writing to the Database from the HMS Vendor interface file."
    assert metadata.report_description == expected_desc
    assert "Report Source State Code:" not in metadata.report_description


def test_opr016_source_type(root_dir: Path):
    doc_path = root_dir / "Report Definition - OPR.docx"
    doc = parse_cognos_docx(doc_path)
    metadata, _ = extract_metadata(doc, doc_path.name)
    assert "OLTP" in metadata.source_type
    assert metadata.source_type != "Report Source Type Component:"


def test_opr016_generated_by(root_dir: Path):
    doc_path = root_dir / "Report Definition - OPR.docx"
    doc = parse_cognos_docx(doc_path)
    metadata, _ = extract_metadata(doc, doc_path.name)
    assert "Other" in metadata.generated_by or "OLTP" in metadata.generated_by
    assert metadata.generated_by != "Report Screen Tip (optional):"


def test_opr004_title_value(root_dir: Path):
    doc_path = root_dir / "Report Definition OPR-TPL-004 - OPR.docx"
    doc = parse_cognos_docx(doc_path)
    metadata, _ = extract_metadata(doc, doc_path.name)
    assert metadata.report_title == "TPL Interface (Input) Exception Report"


def test_opr004_description_value(root_dir: Path):
    doc_path = root_dir / "Report Definition OPR-TPL-004 - OPR.docx"
    doc = parse_cognos_docx(doc_path)
    metadata, _ = extract_metadata(doc, doc_path.name)
    expected_desc = "This report lists the members which had errors while writing to the Database from the interface file."
    assert metadata.report_description == expected_desc


def test_opr004_source_type(root_dir: Path):
    doc_path = root_dir / "Report Definition OPR-TPL-004 - OPR.docx"
    doc = parse_cognos_docx(doc_path)
    metadata, _ = extract_metadata(doc, doc_path.name)
    assert "OLTP" in metadata.source_type


def test_opr005_title_value(root_dir: Path):
    doc_path = root_dir / "Report Definition- OPT-TPL-005.docx"
    doc = parse_cognos_docx(doc_path)
    metadata, _ = extract_metadata(doc, doc_path.name)
    assert metadata.report_title == "TPL Data Match Summary Report"


def test_opr005_description_value(root_dir: Path):
    doc_path = root_dir / "Report Definition- OPT-TPL-005.docx"
    doc = parse_cognos_docx(doc_path)
    metadata, _ = extract_metadata(doc, doc_path.name)
    expected_desc = "This report lists the data match summary information."
    assert metadata.report_description == expected_desc


def test_opr005_frequency(root_dir: Path):
    doc_path = root_dir / "Report Definition- OPT-TPL-005.docx"
    doc = parse_cognos_docx(doc_path)
    metadata, _ = extract_metadata(doc, doc_path.name)
    assert "Scheduled" in metadata.frequency or "Rpt frequency" in metadata.frequency


def test_label_never_becomes_value(root_dir: Path):
    golden_files = [
        "Report Definition - OPR.docx",
        "Report Definition OPR-TPL-004 - OPR.docx",
        "Report Definition- OPT-TPL-005.docx",
    ]
    labels_to_guard = [
        "Report Title:",
        "Report Description:",
        "Report Source State Code:",
        "Report Source Type:",
        "Report Source Type Component:",
        "Report Generated by:",
        "Report Screen Tip (optional):",
        "Report Calendar Type:",
        "Report Frequency Type:",
        "Report Data Accumulation Type:",
    ]
    for filename in golden_files:
        doc_path = root_dir / filename
        doc = parse_cognos_docx(doc_path)
        metadata, _ = extract_metadata(doc, filename)

        for attr in ["report_title", "report_description", "source_type", "generated_by", "frequency"]:
            val = getattr(metadata, attr, "")
            for label in labels_to_guard:
                assert val.strip().lower() != label.strip().lower(), (
                    f"Label '{label}' was incorrectly extracted as value for field '{attr}' in {filename}"
                )
