import json
import hashlib
import os
from pathlib import Path
from datetime import datetime, timezone

from app.cognos.pipeline import run_cognos_pipeline
from app.testing.golden.schemas import (
    GoldenMetadata,
    GoldenRequirement,
    GoldenTestCase,
    GoldenCoverage,
    GoldenTraceability,
    GoldenTraceabilityItem
)

FIXTURES_DIR = Path("backend/tests/fixtures/golden_sources")
GOLDEN_REPORTS_DIR = Path("backend/tests/golden/reports")

def compute_sha256(filepath: Path) -> str:
    hasher = hashlib.sha256()
    with open(filepath, "rb") as f:
        hasher.update(f.read())
    return hasher.hexdigest()

def normalize_requirement(req) -> dict:
    return GoldenRequirement(
        requirement_id=req.requirement_id,
        requirement_area=req.category.value if hasattr(req.category, 'value') else str(req.category),
        statement=getattr(req, 'requirement_text', ""),
        type="CognosRequirement",
        origin=getattr(req, 'origin', "DSD"),
        status=getattr(req, 'status', "active"),
        source_document=getattr(req, 'source_document', None),
        source_section=getattr(req, 'source_section', None),
        source_page=getattr(req, 'source_page', None),
        source_location=None,
        source_table=getattr(req, 'source_table', None),
        source_columns=sorted(req.source_columns) if getattr(req, 'source_columns', None) else [],
        processing_rules=getattr(req, 'processing_rule', None),
        formatting_rules=getattr(req, 'formatting_rule', None),
        comments=sorted(req.open_questions) if getattr(req, 'open_questions', None) else [],
        conflicts=[]
    ).model_dump()

def normalize_test_case(tc) -> dict:
    evidence = []
    if getattr(tc, 'evidence_required', None):
        evidence.append(tc.evidence_required)
    if getattr(tc, 'evidence_type', None):
        evidence.append(tc.evidence_type)
        
    return GoldenTestCase(
        test_case_id=tc.test_case_id,
        requirement_ids=sorted(tc.requirement_ids) if getattr(tc, 'requirement_ids', None) else [],
        scenario=getattr(tc, 'test_case_title', ""),
        test_type=tc.category.value if hasattr(tc.category, 'value') else str(getattr(tc, 'category', "unknown")),
        test_origin=getattr(tc, 'origin', "AutoGenerated"),
        test_design_technique=getattr(tc, 'objective', ""),
        preconditions=getattr(tc, 'preconditions', ""),
        validation_steps=getattr(tc, 'test_steps', ""),
        test_data=getattr(tc, 'test_data', ""),
        expected_result=getattr(tc, 'expected_result', ""),
        priority=getattr(tc, 'priority', "HIGH"),
        evidence_types=sorted(list(set(evidence)))
    ).model_dump()

def generate_golden(report_id: str, docx_filename: str, xml_filename: str | None = None):
    docx_path = FIXTURES_DIR / docx_filename
    xml_path = FIXTURES_DIR / xml_filename if xml_filename else None
    
    if not docx_path.exists():
        print(f"Skipping {report_id} - source docx not found at {docx_path}")
        return
        
    print(f"Generating golden baseline for {report_id}...")
    
    result = run_cognos_pipeline(
        docx_path=docx_path,
        xml_path=xml_path,
        source_document_name=docx_filename,
        target_report_id=report_id
    )
    
    out_dir = GOLDEN_REPORTS_DIR / report_id
    out_dir.mkdir(parents=True, exist_ok=True)
    
    # Requirements
    reqs = [normalize_requirement(r) for r in result.requirement_set.requirements]
    with open(out_dir / "expected_requirements.json", "w") as f:
        json.dump(reqs, f, indent=2)
        
    # Test Cases
    tcs = [normalize_test_case(tc) for tc in result.test_suite.test_cases]
    with open(out_dir / "expected_test_cases.json", "w") as f:
        json.dump(tcs, f, indent=2)
        
    # Coverage
    cov = result.test_suite.coverage
    covered_ids = [t.requirement_id for t in result.test_suite.traceability_matrix if t.coverage_status == "Covered"]
    uncovered_ids = [t.requirement_id for t in result.test_suite.traceability_matrix if t.coverage_status in ("Uncovered", "Partial")]
    
    expected_cov = GoldenCoverage(
        total_dsd_requirements=cov.total_requirements,
        covered_requirement_ids=sorted(covered_ids),
        uncovered_requirement_ids=sorted(uncovered_ids),
        supplemental_test_count=0,
        coverage_percentage=cov.overall_coverage_percentage
    ).model_dump()
    with open(out_dir / "expected_coverage.json", "w") as f:
        json.dump(expected_cov, f, indent=2)
        
    # Traceability
    xml_sha = None
    if getattr(result, 'final_report_context', None) and getattr(result.final_report_context, 'traceability_result', None):
        trace = result.final_report_context.traceability_result
        mappings = []
        for match in getattr(trace, 'field_traces', []):
            mappings.append(GoldenTraceabilityItem(
                requirement_id=match.dsd_field_name,
                xml_path=match.xml_data_item_name,
                match_strategy=match.match_strategy.value if hasattr(match.match_strategy, 'value') else str(match.match_strategy),
                confidence=str(match.confidence),
                implementation_type=match.implementation_type,
                status=match.mapping_status.value if hasattr(match.mapping_status, 'value') else str(match.mapping_status)
            ))
            
        unmapped = [m.item_name for m in getattr(trace, 'implementation_only_items', [])]
        missing = [m.dsd_field_name for m in getattr(trace, 'field_traces', []) if m.mapping_status == "MISSING_IN_XML" or m.mapping_status.value == "MISSING_IN_XML"]
            
        expected_trace = GoldenTraceability(
            report_id=report_id,
            mappings=mappings,
            implementation_only_items=sorted(unmapped),
            missing_in_xml_items=sorted(missing),
            discrepancy_notes=[]
        ).model_dump()
        with open(out_dir / "expected_traceability.json", "w") as f:
            json.dump(expected_trace, f, indent=2)
            
        if xml_path and xml_path.exists():
            xml_sha = compute_sha256(xml_path)
            
    # Metadata
    meta = GoldenMetadata(
        report_id=report_id,
        source_filename=docx_filename,
        source_sha256=compute_sha256(docx_path),
        xml_sha256=xml_sha,
        created_at=datetime.now(timezone.utc).isoformat()
    )
    with open(out_dir / "metadata.json", "w") as f:
        json.dump(meta.model_dump(), f, indent=2)
        
    print(f"Golden files generated for {report_id} successfully.")

if __name__ == "__main__":
    print("WARNING: Golden baseline generation is currently disconnected (P1.10).")
    print("The previous script ran the production pipeline and assumed its output was perfect, ")
    print("which masked regressions and created a self-referential loop.")
    print("Please manually verify any new fixtures independently before updating expectations.")
    # generate_golden("PRV-INT-027", "CR 18175 PRV-INT-027 UT DOCUMENT 1.docx", "PRV-INT-027.xml")
    # generate_golden("OPR-SRA-139", "Service Authorization Part E_CR18140_V0.1 1.docx")
    # generate_golden("OPR-TPL-005", "Report Definition- OPT-TPL-005.docx")
