"""add report_definition_json

Revision ID: 4aaad4f8b611
Revises: de86d3f687c1
Create Date: 2026-08-19 17:47:43.069524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aaad4f8b611'
down_revision: Union[str, Sequence[str], None] = 'de86d3f687c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cognos_generation_runs', sa.Column('report_definition_json', sa.JSON(), nullable=True))
    # op.drop_constraint(None, 'cognos_test_cases', type_='foreignkey')
    # op.drop_column('cognos_test_cases', 'requirement_internal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('cognos_test_cases', sa.Column('requirement_internal_id', sa.INTEGER(), nullable=True))
    # op.create_foreign_key(None, 'cognos_test_cases', 'cognos_requirements', ['requirement_internal_id'], ['id'])
    op.drop_column('cognos_generation_runs', 'report_definition_json')
    # ### end Alembic commands ###
