"""add_source_document_path

Revision ID: 76e5755e462e
Revises: 4aaad4f8b611
Create Date: 2026-08-21 13:06:41.587888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e5755e462e'
down_revision: Union[str, Sequence[str], None] = '4aaad4f8b611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cognos_generation_runs', sa.Column('source_document_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cognos_generation_runs', 'source_document_path')
    # ### end Alembic commands ###
