"""enterprise_jobs

Revision ID: de86d3f687c1
Revises: 0282daef7b91
Create Date: 2026-08-18 17:44:20.451278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de86d3f687c1'
down_revision: Union[str, Sequence[str], None] = '0282daef7b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('background_jobs', sa.Column('job_id', sa.String(), nullable=False))
    op.add_column('background_jobs', sa.Column('job_type', sa.String(), nullable=False))
    op.add_column('background_jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('background_jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('background_jobs', sa.Column('requested_by', sa.String(), nullable=False))
    op.add_column('background_jobs', sa.Column('correlation_id', sa.String(), nullable=True))
    op.add_column('background_jobs', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.add_column('background_jobs', sa.Column('attempt_count', sa.Integer(), nullable=True))
    op.add_column('background_jobs', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.add_column('background_jobs', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('background_jobs', sa.Column('worker_id', sa.String(), nullable=True))
    op.add_column('background_jobs', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('background_jobs', sa.Column('progress', sa.Float(), nullable=True))
    op.add_column('background_jobs', sa.Column('progress_message', sa.String(), nullable=True))
    op.add_column('background_jobs', sa.Column('payload_reference', sa.Text(), nullable=True))
    op.add_column('background_jobs', sa.Column('result_reference', sa.Text(), nullable=True))
    op.add_column('background_jobs', sa.Column('error_code', sa.String(), nullable=True))
    op.add_column('background_jobs', sa.Column('version', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_background_jobs_task_name'), table_name='background_jobs')
    op.create_index(op.f('ix_background_jobs_correlation_id'), 'background_jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_idempotency_key'), 'background_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_background_jobs_job_id'), 'background_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_background_jobs_job_type'), 'background_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_background_jobs_requested_by'), 'background_jobs', ['requested_by'], unique=False)
    op.create_index(op.f('ix_background_jobs_worker_id'), 'background_jobs', ['worker_id'], unique=False)
    op.drop_column('background_jobs', 'payload')
    op.drop_column('background_jobs', 'task_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('background_jobs', sa.Column('task_name', sa.VARCHAR(), nullable=False))
    op.add_column('background_jobs', sa.Column('payload', sa.TEXT(), nullable=False))
    op.drop_index(op.f('ix_background_jobs_worker_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_requested_by'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_job_type'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_job_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_idempotency_key'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_correlation_id'), table_name='background_jobs')
    op.create_index(op.f('ix_background_jobs_task_name'), 'background_jobs', ['task_name'], unique=False)
    op.drop_column('background_jobs', 'version')
    op.drop_column('background_jobs', 'error_code')
    op.drop_column('background_jobs', 'result_reference')
    op.drop_column('background_jobs', 'payload_reference')
    op.drop_column('background_jobs', 'progress_message')
    op.drop_column('background_jobs', 'progress')
    op.drop_column('background_jobs', 'heartbeat_at')
    op.drop_column('background_jobs', 'worker_id')
    op.drop_column('background_jobs', 'priority')
    op.drop_column('background_jobs', 'max_attempts')
    op.drop_column('background_jobs', 'attempt_count')
    op.drop_column('background_jobs', 'idempotency_key')
    op.drop_column('background_jobs', 'correlation_id')
    op.drop_column('background_jobs', 'requested_by')
    op.drop_column('background_jobs', 'completed_at')
    op.drop_column('background_jobs', 'started_at')
    op.drop_column('background_jobs', 'job_type')
    op.drop_column('background_jobs', 'job_id')
    # ### end Alembic commands ###
