"""
Metadata extractor — Part 2.

Extracts report-level metadata from the "Report Definition" section of a
Cognos report specification with:
- Strict label vs. value separation (label text can NEVER become value)
- Isolated field extraction (never merge Description, Source State Code, etc.)
- Checkbox selection semantics (extract checked options like OLTP, Calendar, Other: OLTP)
- Complete description string preservation
"""

from __future__ import annotations

import re
from typing import Optional

from app.domain.cognos_models import (
    ReportMetadata, ReportType, SourceReference,
)
from app.services.cognos_docx_parser import (
    CognosParsedDocument, CheckboxState, ParsedTable, ParsedRow, ParsedCell,
)


_METADATA_KEY_MAP = {
    # Report ID
    "report id": "report_id",
    "client report id": "client_report_id",
    "report number": "report_id",
    "rpt id": "report_id",
    # Title
    "report title": "report_title",
    "title": "report_title",
    "report name": "report_title",
    # Description
    "report description": "report_description",
    "description": "report_description",
    "business purpose": "report_description",
    # Type
    "report type": "report_type",
    # Client
    "client": "client",
    "client name": "client",
    # LOB
    "line of business": "lob",
    "lob": "lob",
    "client line of business": "lob",
    # Department
    "division": "division_department",
    "department": "division_department",
    "division / department": "division_department",
    "division/department": "division_department",
    "client division/department": "division_department",
    # Source State Code
    "report source state code": "source_state_code",
    "source state code": "source_state_code",
    # Source Type
    "report source type": "source_type",
    "source type": "source_type",
    # Source Component
    "report source type component": "source_component",
    "source component": "source_component",
    "component": "source_component",
    # Generated By
    "report generated by": "generated_by",
    "generated by": "generated_by",
    # Screen Tip
    "report screen tip": "screen_tip",
    "screen tip": "screen_tip",
    "report screen tip (optional)": "screen_tip",
    # Calendar Type
    "report calendar type": "calendar_type",
    "calendar type": "calendar_type",
    # Frequency
    "report frequency type": "frequency",
    "frequency type": "frequency",
    "frequency": "frequency",
    "report frequency": "frequency",
    # Data Accumulation
    "report data accumulation type": "data_accumulation_type",
    "data accumulation type": "data_accumulation_type",
    "data accumulation": "data_accumulation_type",
}

# Set of normalized label names to guard against returning labels as values
_KNOWN_LABEL_STRINGS = {
    "nh mmis report definition",
    "report type:",
    "client name:",
    "client report id:",
    "client line of business:",
    "client division/department:",
    "report title:",
    "report description:",
    "report source state code:",
    "report source type:",
    "report source type component:",
    "report generation",
    "report generated by:",
    "report screen tip (optional):",
    "report calendar type:",
    "report frequency type:",
    "report data accumulation type:",
    "report selection criteria:",
    "report field",
}


def _normalize_key(key: str) -> str:
    """Normalize a key for matching."""
    return re.sub(r"\s+", " ", key.strip().lower().rstrip(":"))


def _is_label_text(text: str) -> bool:
    """Check if text is a field label rather than a metadata value."""
    if not text:
        return True
    cleaned = text.strip().lower()
    if cleaned in _KNOWN_LABEL_STRINGS:
        return True
    if cleaned in _METADATA_KEY_MAP:
        return True
    if cleaned.endswith(":") and len(cleaned) < 50:
        return True
    return False


def _is_valid_value(canonical: str, raw_key: str, val: str) -> bool:
    """Validate that val is not empty, not a label, and not key echo."""
    if not val:
        return False
    if _is_label_text(val):
        return False
    clean_val = val.strip().rstrip(":").lower()
    clean_key = raw_key.strip().rstrip(":").lower()
    if clean_val == clean_key:
        return False
    return True


def extract_metadata(
    doc: CognosParsedDocument,
    source_document_name: str = "",
) -> tuple[ReportMetadata, list[str]]:
    """
    Extract report metadata from the parsed DOCX with strict label/value separation.
    Returns (ReportMetadata, warnings).
    """
    metadata = ReportMetadata(
        source=SourceReference(
            document_name=source_document_name,
            section="Report Definition",
        )
    )
    warnings: list[str] = []

    report_def_section = doc.get_section("Report Definition")
    if report_def_section and report_def_section.source_page:
        metadata.source.page = report_def_section.source_page

    # Direct row-by-row structural scan over parsed tables
    parsed_tables = doc.all_parsed_tables
    if report_def_section and report_def_section.tables:
        parsed_tables = report_def_section.tables

    for parsed_table in parsed_tables:
        for row in parsed_table.rows:
            if not row.cells:
                continue

            cell0_text = row.cells[0].text.strip()
            norm_key = _normalize_key(cell0_text)
            if norm_key not in _METADATA_KEY_MAP:
                # Try cell 1 if cell 0 is empty
                if len(row.cells) > 1:
                    cell0_text = row.cells[1].text.strip()
                    norm_key = _normalize_key(cell0_text)

            if norm_key in _METADATA_KEY_MAP:
                canonical = _METADATA_KEY_MAP[norm_key]
                current_val = getattr(metadata, canonical, "")

                # 1. Check cell-level checkboxes
                checked_items = []
                has_checkboxes = False
                for cell in row.cells[1:]:
                    if cell.checkbox_labels:
                        has_checkboxes = True
                    for cb in cell.checkbox_labels:
                        if cb.get("checked") or cb.get("state") == CheckboxState.CHECKED:
                            checked_items.append(cb["label"])

                if has_checkboxes:
                    if checked_items:
                        # Format extracted checkbox value
                        val_str = ", ".join(dict.fromkeys(checked_items))
                        if canonical == "report_type":
                            if "standard" in val_str.lower():
                                metadata.report_type = ReportType.STANDARD
                            elif "customized" in val_str.lower():
                                metadata.report_type = ReportType.CUSTOMIZED
                        elif canonical == "frequency":
                            # Clean up "Other - Please explain: Event Driven ..."
                            if "event driven" in val_str.lower():
                                metadata.frequency = "Event Driven"
                            else:
                                metadata.frequency = val_str
                        else:
                            setattr(metadata, canonical, val_str)
                    else:
                        # Selection state cannot be reliably determined.
                        if canonical == "report_type":
                            metadata.report_type = ReportType.UNKNOWN
                        elif canonical == "frequency":
                            metadata.frequency = "REVIEW_REQUIRED"
                        else:
                            setattr(metadata, canonical, "REVIEW_REQUIRED")
                    continue

                # 2. Extract plain text from value column(s) (cells[2:])
                if not current_val or current_val.lower() == norm_key:
                    value_candidates = []
                    for cell in row.cells[2:]:
                        c_text = cell.text.strip()
                        if c_text and not _is_label_text(c_text):
                            value_candidates.append(c_text)

                    if not value_candidates and len(row.cells) > 1:
                        c1_text = row.cells[1].text.strip()
                        if c1_text and not _is_label_text(c1_text):
                            value_candidates.append(c1_text)

                    if value_candidates:
                        val = value_candidates[0]
                        if canonical == "report_type":
                            if "standard" in val.lower():
                                metadata.report_type = ReportType.STANDARD
                            elif "customized" in val.lower():
                                metadata.report_type = ReportType.CUSTOMIZED
                        elif canonical == "frequency":
                            if "event driven" in val.lower():
                                metadata.frequency = "Event Driven"
                            elif "scheduled" in val.lower():
                                metadata.frequency = "Scheduled"
                            else:
                                metadata.frequency = val
                        else:
                            setattr(metadata, canonical, val)

    # Secondary paragraph scan for Report ID & Title if still unpopulated
    if not metadata.report_id or _is_label_text(metadata.report_id):
        metadata.report_id = _detect_report_id_from_text(doc)

    if not metadata.report_title or _is_label_text(metadata.report_title):
        for para in doc.all_paragraphs:
            if "report title:" in para.lower():
                parts = para.split(":", 1)
                if len(parts) > 1:
                    candidate = parts[1].strip()
                    if candidate and not _is_label_text(candidate):
                        metadata.report_title = candidate
                        break

    return metadata, warnings


def _detect_report_id_from_text(doc: CognosParsedDocument) -> str:
    """Detect Report ID from paragraph text using regex."""
    report_id_pattern = re.compile(r"\b([A-Z]{2,4}-[A-Z]{2,4}-\d{3,})\b")
    for para in doc.all_paragraphs:
        match = report_id_pattern.search(para)
        if match:
            return match.group(1)
    return ""

